SR-3 Add the Recruiter, Leader, Team and Question models
informatyzacja-sspwr-projekty/recruitment-system pull request #1
Opened 2022-08-09 08:22 UTC by Mendrejk

Based on the MVP ERD: https://informatyzacja.atlassian.net/browse/SR-3

2022-08-09 08:27 UTC, DocentSzachista submitted a review, later dismissed

2022-08-09 09:00 UTC, deamacto requested changes

2022-08-09 09:00 UTC, deamacto commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/model/Recruiter.kt
> +    val teams: MutableList<Team>
Nie lepiej zrobić MutableSet?

2022-08-09 09:00 UTC, deamacto commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/model/Team.kt
> +    val recruiters: MutableList<Recruiter>
Tutaj też MutableSet

2022-08-09 09:18 UTC, Mendrejk commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/model/Recruiter.kt
> +    val teams: MutableList<Team>
Updated

2022-08-09 09:18 UTC, Mendrejk commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/model/Team.kt
> +    val recruiters: MutableList<Recruiter>
Updated

2022-08-09 09:20 UTC, Mendrejk commented
Used MutableSets for collections of Teams and Recruiters. Overriden equals so that Leader and Recruiter are compared only by email and Team is compared only by name.

2022-08-09 21:52 UTC, deamacto requested changes

2022-08-09 21:52 UTC, deamacto commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/model/Leader.kt
> +        if (email != other.email) {
Może zamiast tego zrobić return email == other.email?

2022-08-09 21:52 UTC, deamacto commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/model/Recruiter.kt
> +        if (email != other.email) {
Tutaj też return email == other.email

2022-08-09 21:52 UTC, deamacto commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/model/Team.kt
> +        if (name != other.name) {
return name == other.name

2022-08-10 08:34 UTC, Mendrejk commented
Simplified return statements

2022-08-10 13:33 UTC, deamacto approved these changes

2022-08-10 16:39 UTC, DocentSzachista approved these changes

2022-08-10 16:40 UTC, Bravo555 commented on backend/recruitment-system/src/main/kotlin/pl/edu/pwr/samorzad/informatyzacja/recruitmentsystem/model/Leader.kt
> +        other as Leader
All looks straightforward, but could you tell me what's the purpose of this expression? The docs say that it's just a cast, but what's happening with the result of this cast? It isn't assigned to a variable and isn't returned. Is it modified in place?

2022-08-10 16:40 UTC, Bravo555 approved these changes

2022-08-10 16:54 UTC, merged